-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.auth_group
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    name character varying(150) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT auth_group_pkey PRIMARY KEY (id),
    CONSTRAINT auth_group_name_key UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS public.auth_group_permissions
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    group_id integer NOT NULL,
    permission_id integer NOT NULL,
    CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id),
    CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id)
);

CREATE TABLE IF NOT EXISTS public.auth_permission
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT auth_permission_pkey PRIMARY KEY (id),
    CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename)
);

CREATE TABLE IF NOT EXISTS public.auth_user
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    password character varying(128) COLLATE pg_catalog."default" NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) COLLATE pg_catalog."default" NOT NULL,
    first_name character varying(150) COLLATE pg_catalog."default" NOT NULL,
    last_name character varying(150) COLLATE pg_catalog."default" NOT NULL,
    email character varying(254) COLLATE pg_catalog."default" NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL,
    CONSTRAINT auth_user_pkey PRIMARY KEY (id),
    CONSTRAINT auth_user_username_key UNIQUE (username)
);

CREATE TABLE IF NOT EXISTS public.auth_user_groups
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    user_id integer NOT NULL,
    group_id integer NOT NULL,
    CONSTRAINT auth_user_groups_pkey PRIMARY KEY (id),
    CONSTRAINT auth_user_groups_user_id_group_id_94350c0c_uniq UNIQUE (user_id, group_id)
);

CREATE TABLE IF NOT EXISTS public.auth_user_user_permissions
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    user_id integer NOT NULL,
    permission_id integer NOT NULL,
    CONSTRAINT auth_user_user_permissions_pkey PRIMARY KEY (id),
    CONSTRAINT auth_user_user_permissions_user_id_permission_id_14a6b632_uniq UNIQUE (user_id, permission_id)
);

CREATE TABLE IF NOT EXISTS public.django_admin_log
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    action_time timestamp with time zone NOT NULL,
    object_id text COLLATE pg_catalog."default",
    object_repr character varying(200) COLLATE pg_catalog."default" NOT NULL,
    action_flag smallint NOT NULL,
    change_message text COLLATE pg_catalog."default" NOT NULL,
    content_type_id integer,
    user_id integer NOT NULL,
    CONSTRAINT django_admin_log_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.django_content_type
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    app_label character varying(100) COLLATE pg_catalog."default" NOT NULL,
    model character varying(100) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT django_content_type_pkey PRIMARY KEY (id),
    CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model)
);

CREATE TABLE IF NOT EXISTS public.django_migrations
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    app character varying(255) COLLATE pg_catalog."default" NOT NULL,
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    applied timestamp with time zone NOT NULL,
    CONSTRAINT django_migrations_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.django_session
(
    session_key character varying(40) COLLATE pg_catalog."default" NOT NULL,
    session_data text COLLATE pg_catalog."default" NOT NULL,
    expire_date timestamp with time zone NOT NULL,
    CONSTRAINT django_session_pkey PRIMARY KEY (session_key)
);

CREATE TABLE IF NOT EXISTS public.formulario_actividad_cultura
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    nombre character varying(100) COLLATE pg_catalog."default" NOT NULL,
    descripcion text COLLATE pg_catalog."default",
    CONSTRAINT formulario_actividad_cultura_pkey PRIMARY KEY (id),
    CONSTRAINT formulario_actividad_cultura_nombre_key UNIQUE (nombre)
);

CREATE TABLE IF NOT EXISTS public.formulario_acudiente
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    nombre character varying(100) COLLATE pg_catalog."default" NOT NULL,
    telefono character varying(15) COLLATE pg_catalog."default" NOT NULL,
    ocupacion character varying(100) COLLATE pg_catalog."default" NOT NULL,
    parentesco character varying(50) COLLATE pg_catalog."default" NOT NULL,
    direccion text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT formulario_acudiente_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.formulario_asistencia
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    fecha_asistencia date,
    clase_id bigint NOT NULL,
    alumno_id bigint,
    CONSTRAINT formulario_asistencia_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.formulario_clase
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    fecha_clase date NOT NULL,
    cupo_maximo integer NOT NULL,
    cupo_actual integer NOT NULL,
    curso_id bigint NOT NULL,
    docente_id bigint NOT NULL,
    CONSTRAINT formulario_clase_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.formulario_curso
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    nombre character varying(50) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT formulario_curso_pkey PRIMARY KEY (id),
    CONSTRAINT formulario_curso_nombre_key UNIQUE (nombre)
);

CREATE TABLE IF NOT EXISTS public.formulario_cursoextendido
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    tipo_curso character varying(20) COLLATE pg_catalog."default" NOT NULL,
    disciplina character varying(50) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT formulario_cursoextendido_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.formulario_datos_complementarios
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    identidad_genero character varying(20) COLLATE pg_catalog."default" NOT NULL,
    grupo_etnico character varying(20) COLLATE pg_catalog."default" NOT NULL,
    discapacidad character varying(20) COLLATE pg_catalog."default" NOT NULL,
    tipo_discapacidad character varying(50) COLLATE pg_catalog."default",
    enfermedad_huerfana boolean NOT NULL,
    enfermedad_nombre character varying(100) COLLATE pg_catalog."default",
    conflicto_armado boolean NOT NULL,
    tipo_sangre character varying(5) COLLATE pg_catalog."default" NOT NULL,
    otro_nivel_educativo character varying(100) COLLATE pg_catalog."default",
    pertenece_organizacion boolean NOT NULL,
    nombre_organizacion character varying(100) COLLATE pg_catalog."default",
    participante_id bigint NOT NULL,
    CONSTRAINT formulario_datos_complementarios_pkey PRIMARY KEY (id),
    CONSTRAINT formulario_datos_complementarios_participante_id_key UNIQUE (participante_id)
);

CREATE TABLE IF NOT EXISTS public.formulario_datos_complementarios_nivel_educativo
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    datoscomplementarios_id bigint NOT NULL,
    niveleducativo_id bigint NOT NULL,
    CONSTRAINT formulario_datos_complementarios_nivel_educativo_pkey PRIMARY KEY (id),
    CONSTRAINT formulario_datos_complem_datoscomplementarios_id__26476315_uniq UNIQUE (datoscomplementarios_id, niveleducativo_id)
);

CREATE TABLE IF NOT EXISTS public.formulario_docente
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    nombre character varying(100) COLLATE pg_catalog."default" NOT NULL,
    identificacion character varying(30) COLLATE pg_catalog."default" NOT NULL,
    correo character varying(254) COLLATE pg_catalog."default" NOT NULL,
    direccion character varying(255) COLLATE pg_catalog."default",
    telefono character varying(30) COLLATE pg_catalog."default",
    fecha_nacimiento date,
    area_encargada character varying(50) COLLATE pg_catalog."default",
    CONSTRAINT formulario_docente_pkey PRIMARY KEY (id),
    CONSTRAINT formulario_docente_correo_key UNIQUE (correo),
    CONSTRAINT formulario_docente_identificacion_key UNIQUE (identificacion)
);

CREATE TABLE IF NOT EXISTS public.formulario_docente_cursos
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    docente_id bigint NOT NULL,
    curso_id bigint NOT NULL,
    CONSTRAINT formulario_docente_cursos_pkey PRIMARY KEY (id),
    CONSTRAINT formulario_docente_cursos_docente_id_curso_id_b875a255_uniq UNIQUE (docente_id, curso_id)
);

CREATE TABLE IF NOT EXISTS public.formulario_nivel_educativo
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    nombre character varying(50) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT formulario_nivel_educativo_pkey PRIMARY KEY (id),
    CONSTRAINT formulario_nivel_educativo_nombre_key UNIQUE (nombre)
);

CREATE TABLE IF NOT EXISTS public.formulario_participante
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    nombre character varying(100) COLLATE pg_catalog."default" NOT NULL,
    identificacion character varying(30) COLLATE pg_catalog."default" NOT NULL,
    correo character varying(254) COLLATE pg_catalog."default" NOT NULL,
    direccion text COLLATE pg_catalog."default",
    telefono character varying(30) COLLATE pg_catalog."default",
    fecha_nacimiento date,
    curso_id bigint,
    edad integer,
    fecha_expedicion date,
    tipo_documento character varying(2) COLLATE pg_catalog."default" NOT NULL,
    fecha_inscripcion date NOT NULL,
    area character varying(10) COLLATE pg_catalog."default" NOT NULL,
    barrio character varying(100) COLLATE pg_catalog."default",
    ciudad character varying(100) COLLATE pg_catalog."default" NOT NULL,
    localidad character varying(100) COLLATE pg_catalog."default" NOT NULL,
    lugar_expedicion character varying(100) COLLATE pg_catalog."default",
    pais_origen character varying(50) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT formulario_participante_pkey PRIMARY KEY (id),
    CONSTRAINT formulario_participante_correo_key UNIQUE (correo),
    CONSTRAINT formulario_participante_identificacion_key UNIQUE (identificacion)
);

CREATE TABLE IF NOT EXISTS public.formulario_proyecto
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    nombre character varying(100) COLLATE pg_catalog."default" NOT NULL,
    descripcion text COLLATE pg_catalog."default",
    fecha_inicio date NOT NULL,
    fecha_fin date,
    CONSTRAINT formulario_proyecto_pkey PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id)
    REFERENCES public.auth_permission (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS auth_group_permissions_permission_id_84c5c92e
    ON public.auth_group_permissions(permission_id);


ALTER TABLE IF EXISTS public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id)
    REFERENCES public.auth_group (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS auth_group_permissions_group_id_b120cbf9
    ON public.auth_group_permissions(group_id);


ALTER TABLE IF EXISTS public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id)
    REFERENCES public.django_content_type (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS auth_permission_content_type_id_2f476e4b
    ON public.auth_permission(content_type_id);


ALTER TABLE IF EXISTS public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_group_id_97559544_fk_auth_group_id FOREIGN KEY (group_id)
    REFERENCES public.auth_group (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS auth_user_groups_group_id_97559544
    ON public.auth_user_groups(group_id);


ALTER TABLE IF EXISTS public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_6a12ed8b_fk_auth_user_id FOREIGN KEY (user_id)
    REFERENCES public.auth_user (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS auth_user_groups_user_id_6a12ed8b
    ON public.auth_user_groups(user_id);


ALTER TABLE IF EXISTS public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm FOREIGN KEY (permission_id)
    REFERENCES public.auth_permission (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS auth_user_user_permissions_permission_id_1fbb5f2c
    ON public.auth_user_user_permissions(permission_id);


ALTER TABLE IF EXISTS public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id FOREIGN KEY (user_id)
    REFERENCES public.auth_user (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS auth_user_user_permissions_user_id_a95ead1b
    ON public.auth_user_user_permissions(user_id);


ALTER TABLE IF EXISTS public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id)
    REFERENCES public.django_content_type (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS django_admin_log_content_type_id_c4bce8eb
    ON public.django_admin_log(content_type_id);


ALTER TABLE IF EXISTS public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_auth_user_id FOREIGN KEY (user_id)
    REFERENCES public.auth_user (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS django_admin_log_user_id_c564eba6
    ON public.django_admin_log(user_id);


ALTER TABLE IF EXISTS public.formulario_asistencia
    ADD CONSTRAINT formulario_asistenci_alumno_id_b7074e6e_fk_formulari FOREIGN KEY (alumno_id)
    REFERENCES public.formulario_participante (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS formulario_asistencia_alumno_id_b7074e6e
    ON public.formulario_asistencia(alumno_id);


ALTER TABLE IF EXISTS public.formulario_asistencia
    ADD CONSTRAINT formulario_asistencia_clase_id_ae00cf65_fk_formulario_clase_id FOREIGN KEY (clase_id)
    REFERENCES public.formulario_clase (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS formulario_asistencia_clase_id_ae00cf65
    ON public.formulario_asistencia(clase_id);


ALTER TABLE IF EXISTS public.formulario_clase
    ADD CONSTRAINT formulario_clase_curso_id_b99ee682_fk_formulario_curso_id FOREIGN KEY (curso_id)
    REFERENCES public.formulario_curso (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS formulario_clase_curso_id_b99ee682
    ON public.formulario_clase(curso_id);


ALTER TABLE IF EXISTS public.formulario_clase
    ADD CONSTRAINT formulario_clase_docente_id_11e09028_fk_formulario_docente_id FOREIGN KEY (docente_id)
    REFERENCES public.formulario_docente (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS formulario_clase_docente_id_11e09028
    ON public.formulario_clase(docente_id);


ALTER TABLE IF EXISTS public.formulario_datos_complementarios
    ADD CONSTRAINT formulario_datos_com_participante_id_d8a3401d_fk_formulari FOREIGN KEY (participante_id)
    REFERENCES public.formulario_participante (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS formulario_datos_complementarios_participante_id_key
    ON public.formulario_datos_complementarios(participante_id);


ALTER TABLE IF EXISTS public.formulario_datos_complementarios_nivel_educativo
    ADD CONSTRAINT formulario_datos_com_datoscomplementarios_44e6764e_fk_formulari FOREIGN KEY (datoscomplementarios_id)
    REFERENCES public.formulario_datos_complementarios (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS formulario_datos_complemen_datoscomplementarios_id_44e6764e
    ON public.formulario_datos_complementarios_nivel_educativo(datoscomplementarios_id);


ALTER TABLE IF EXISTS public.formulario_datos_complementarios_nivel_educativo
    ADD CONSTRAINT formulario_datos_com_niveleducativo_id_f27813a3_fk_formulari FOREIGN KEY (niveleducativo_id)
    REFERENCES public.formulario_nivel_educativo (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS formulario_datos_complemen_niveleducativo_id_f27813a3
    ON public.formulario_datos_complementarios_nivel_educativo(niveleducativo_id);


ALTER TABLE IF EXISTS public.formulario_docente_cursos
    ADD CONSTRAINT formulario_docente_c_curso_id_e0a0defc_fk_formulari FOREIGN KEY (curso_id)
    REFERENCES public.formulario_curso (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS formulario_docente_cursos_curso_id_e0a0defc
    ON public.formulario_docente_cursos(curso_id);


ALTER TABLE IF EXISTS public.formulario_docente_cursos
    ADD CONSTRAINT formulario_docente_c_docente_id_68d9b0e1_fk_formulari FOREIGN KEY (docente_id)
    REFERENCES public.formulario_docente (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS formulario_docente_cursos_docente_id_68d9b0e1
    ON public.formulario_docente_cursos(docente_id);


ALTER TABLE IF EXISTS public.formulario_participante
    ADD CONSTRAINT formulario_participa_curso_id_c2570eca_fk_formulari FOREIGN KEY (curso_id)
    REFERENCES public.formulario_curso (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS formulario_participante_curso_id_c2570eca
    ON public.formulario_participante(curso_id);

END;