# Generated by Django 5.1.6 on 2025-03-19 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participante',
            name='edad',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='participante',
            name='fecha_expedicion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='participante',
            name='tipo_documento',
            field=models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('TI', 'Tarjeta de Identidad'), ('CE', 'Cédula de Extranjería')], default='CC', max_length=2),
        ),
        migrations.AlterField(
            model_name='curso',
            name='nombre',
            field=models.CharField(choices=[('Fútbol', 'Fútbol'), ('Basketball', 'Basketball'), ('Voleibol', 'Voleibol'), ('Danza', 'Danza'), ('Fotografía', 'Fotografía')], max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='docente',
            name='area_encargada',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='participante',
            name='identificacion',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='participante',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='participante',
            name='telefono',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
