# Generated by Django 5.1.6 on 2025-03-19 02:55

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0002_participante_edad_participante_fecha_expedicion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistencia',
            name='estado',
            field=models.CharField(choices=[('Presente', 'Presente'), ('Ausente', 'Ausente')], default='Presente', max_length=10),
        ),
        migrations.AddField(
            model_name='participante',
            name='fecha_inscripcion',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='fecha_asistencia',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_pago', models.DateField(default=datetime.date.today)),
                ('metodo_pago', models.CharField(choices=[('Efectivo', 'Efectivo'), ('Transferencia', 'Transferencia')], max_length=50)),
                ('participante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formulario.participante')),
            ],
            options={
                'db_table': 'formulario_pago',
            },
        ),
    ]
