# Generated by Django 5.1.6 on 2025-03-20 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0004_remove_asistencia_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='participante',
            name='area',
            field=models.CharField(choices=[('Rural', 'Rural'), ('Urbano', 'Urbano')], default='Urbano', max_length=10),
        ),
        migrations.AddField(
            model_name='participante',
            name='barrio',
            field=models.CharField(blank=True, choices=[('Agrupación Pio X', 'Agrupación Pio X'), ('Carvajal II Sector', 'Carvajal II Sector'), ('Ciudad Kennedy', 'Ciudad Kennedy'), ('Mandalay I Sector', 'Mandalay I Sector'), ('Nueva Marsella', 'Nueva Marsella'), ('San Juan del Castillo', 'San Juan del Castillo'), ('Urb. Castilla', 'Urb. Castilla')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='participante',
            name='ciudad',
            field=models.CharField(default='Bogotá', max_length=100),
        ),
        migrations.AddField(
            model_name='participante',
            name='localidad',
            field=models.CharField(default='Kennedy', max_length=100),
        ),
        migrations.AddField(
            model_name='participante',
            name='lugar_expedicion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='participante',
            name='pais_origen',
            field=models.CharField(choices=[('Colombia', 'Colombia'), ('Afganistán', 'Afganistán'), ('Alemania', 'Alemania'), ('Argentina', 'Argentina'), ('Brasil', 'Brasil'), ('Canadá', 'Canadá'), ('Estados Unidos', 'Estados Unidos'), ('Francia', 'Francia'), ('Venezuela', 'Venezuela'), ('Vietnam', 'Vietnam'), ('Zimbabue', 'Zimbabue')], default='Colombia', max_length=50),
        ),
    ]
