# Generated by Django 5.1.6 on 2025-03-23 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0006_acudiente_niveleducativo_alter_participante_barrio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CursoExtendido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_curso', models.CharField(choices=[('Deporte', 'Deporte'), ('Cultura', 'Cultura')], max_length=20)),
                ('disciplina', models.CharField(max_length=50)),
            ],
        ),
    ]
