# Generated by Django 5.1.6 on 2025-03-23 21:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0007_cursoextendido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursoextendido',
            name='disciplina',
            field=models.CharField(choices=[('Fútbol', 'Fútbol'), ('Basketball', 'Basketball'), ('Voleibol', 'Voleibol'), ('Danza', 'Danza'), ('Fotografía', 'Fotografía'), ('Pintura', 'Pintura')], max_length=50),
        ),
        migrations.AlterField(
            model_name='datoscomplementarios',
            name='tipo_sangre',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=5),
        ),
        migrations.CreateModel(
            name='DocumentoRequisito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formulario_inscripcion_firmado', models.FileField(upload_to='documentos/')),
                ('documento_identidad', models.FileField(upload_to='documentos/')),
                ('certificado_eps', models.FileField(upload_to='documentos/')),
                ('certificacion_residencia', models.FileField(upload_to='documentos/')),
                ('consentimiento_informado', models.FileField(upload_to='documentos/')),
                ('participante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formulario.participante')),
            ],
            options={
                'db_table': 'formulario_documento_requisito',
            },
        ),
    ]
