# Generated by Django 5.1.6 on 2025-03-24 22:34

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0008_alter_cursoextendido_disciplina_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='acudiente',
            name='participante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='acudientes', to='formulario.participante'),
        ),
        migrations.AlterField(
            model_name='acudiente',
            name='telefono',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='El teléfono debe contener solo números.', regex='^\\\\d{7,15}$')], verbose_name='Teléfono'),
        ),
    ]
