# Generated by Django 5.1.6 on 2025-03-30 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0009_acudiente_participante_alter_acudiente_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursoextendido',
            name='disciplina',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cursoextendido',
            name='tipo_curso',
            field=models.CharField(max_length=100),
        ),
    ]
