# Generated by Django 5.1.6 on 2025-03-30 22:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0010_alter_cursoextendido_disciplina_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='participante',
            name='curso_extendido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participantes', to='formulario.cursoextendido'),
        ),
        migrations.AlterModelTable(
            name='cursoextendido',
            table='formulario_curso_extendido',
        ),
    ]
