# Generated by Django 5.1.6 on 2025-03-30 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0011_participante_curso_extendido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursoextendido',
            name='tipo_curso',
            field=models.CharField(choices=[('Deporte', 'Deporte'), ('Cultura', 'Cultura')], max_length=20),
        ),
    ]
