# Generated by Django 5.1.6 on 2025-03-31 00:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0012_alter_cursoextendido_tipo_curso'),
    ]

    operations = [
        migrations.AddField(
            model_name='cursoextendido',
            name='docente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='formulario.docente'),
        ),
        migrations.AddField(
            model_name='cursoextendido',
            name='horario',
            field=models.CharField(default='Por definir', max_length=100),
        ),
        migrations.AddField(
            model_name='cursoextendido',
            name='lugar',
            field=models.CharField(default='Por definir', max_length=150),
        ),
        migrations.AlterModelTable(
            name='cursoextendido',
            table=None,
        ),
    ]
