# Generated by Django 5.1.6 on 2025-03-31 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0013_cursoextendido_docente_cursoextendido_horario_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='docente',
            name='cursos',
        ),
        migrations.AddField(
            model_name='docente',
            name='disciplina',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='docente',
            name='area_encargada',
            field=models.CharField(blank=True, choices=[('Deporte', 'Deporte'), ('Cultura', 'Cultura')], max_length=50, null=True),
        ),
    ]
