# Generated by Django 5.1.6 on 2025-03-31 20:45

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0014_remove_docente_cursos_docente_disciplina_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('tipo', models.CharField(choices=[('Deporte', 'Deporte'), ('Cultura', 'Cultura')], max_length=20)),
            ],
            options={
                'db_table': 'formulario_disciplina',
            },
        ),
        migrations.AlterField(
            model_name='acudiente',
            name='nombre',
            field=models.CharField(max_length=50, verbose_name='Nombre del Acudiente'),
        ),
        migrations.AlterField(
            model_name='acudiente',
            name='telefono',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='El teléfono debe contener solo números (7 a 15 dígitos).', regex='^\\d{7,15}$')], verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='datoscomplementarios',
            name='discapacidad',
            field=models.CharField(choices=[('No', 'No'), ('Sí', 'Sí')], default='No', max_length=20),
        ),
        migrations.AlterField(
            model_name='cursoextendido',
            name='disciplina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formulario.disciplina'),
        ),
    ]
