# Generated by Django 5.1.6 on 2025-04-01 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0015_disciplina_alter_acudiente_nombre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursoextendido',
            name='horario',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cursoextendido',
            name='lugar',
            field=models.CharField(max_length=150),
        ),
    ]
