# Generated by Django 5.1.6 on 2025-04-02 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0016_alter_cursoextendido_horario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplina',
            name='tipo',
            field=models.CharField(choices=[('Deporte', 'Deporte'), ('Cultura', 'Cultura')], max_length=10),
        ),
        migrations.AlterModelTable(
            name='disciplina',
            table=None,
        ),
    ]
