"""
Django settings for proyecto project.

Generated by 'django-admin startproject' using Django 5.1.6.
"""

from pathlib import Path
import os
from dotenv import load_dotenv  # 🔹 Para manejar variables de entorno de manera segura

# Cargar variables de entorno desde un archivo .env (si existe)
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# 🔹 Seguridad en el manejo de la clave secreta
SECRET_KEY = os.getenv("SECRET_KEY", "django-insecure-al_oom3#wac0_wjv!-n%gm11$g5y_(787c_d@rhu3$be$)w(#l")

# SECURITY WARNING: Don't run with debug turned on in production!
DEBUG = True # Cambiar a False en producción

# 🔹 Asegurar que ALLOWED_HOSTS contenga al menos localhost
ALLOWED_HOSTS = os.getenv("ALLOWED_HOSTS", "127.0.0.1,localhost").split(",")

# 🔹 Configuración para evitar errores de CSRF en entornos seguros
CSRF_TRUSTED_ORIGINS = [
    "http://127.0.0.1",
    "http://localhost",
]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'formulario',  # ✅ Asegúrate de que esté aquí
    'widget_tweaks',
]
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'proyecto.urls'

import os

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'formulario', 'templates'),
        ],  
        'APP_DIRS': True,  # Importante para que Django busque en las apps registradas
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


WSGI_APPLICATION = 'proyecto.wsgi.application'

# 🔹 Configuración de la base de datos con PostgreSQL
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv("DB_NAME", "basedpc"),
        'USER': os.getenv("DB_USER", "postgres"),
        'PASSWORD': os.getenv("DB_PASSWORD", "Tita1422"),
        'HOST': os.getenv("DB_HOST", "localhost"),
        'PORT': os.getenv("DB_PORT", "5432"),
    }
}

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# Internationalization
LANGUAGE_CODE = 'es-co'  # 🔹 Configurado para español de Colombia
TIME_ZONE = 'America/Bogota'  # 🔹 Configuración correcta para la hora local
USE_I18N = True
USE_TZ = True

# 🔹 Configuración de archivos estáticos (CSS, JavaScript, Imágenes)
STATIC_URL = '/static/'

# Asegurar que Django encuentra la carpeta de archivos estáticos
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'formulario/static'),  # Ruta correcta
]

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
